package com.penallaw.backend.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Tracks unique visitor events across the entire lifetime of the application.
 * One row = one unique (visitor_id, visit_date) pair.
 * The UNIQUE constraint on (visitor_id, visit_date) prevents double-counting —
 * duplicate inserts are silently ignored by the service, so the count is always accurate.
 *
 * visitor_id: a UUID generated by the browser, stored in localStorage (persists across tabs/pages).
 * visit_date: the calendar date of the visit (UTC).
 *
 * Total visitor count = SELECT COUNT(*) FROM visitor_logs  →  total unique visit events ever recorded.
 */
@Entity
@Table(
    name = "visitor_logs",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_visitor_logs_visitor_date",
        columnNames = {"visitor_id", "visit_date"}
    )
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VisitorLog {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "visitor_id", nullable = false, length = 64)
    private String visitorId;

    @Column(name = "visit_date", nullable = false)
    private LocalDate visitDate;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;
}
